### ISSUE TITLE
Erro no endereço

### ISSUE THREAD

**Issue by pablotischer** [tiagosampaio/OsStudios_PagSeguroApi#1]
Tiago, instalei o novo módulo para testar, mas quando confirmo o checkout e está redirecionando para o PagSeguro, dá um erro nos campos de endereço.
Já tinha testado o seu módulo anterior, o mesmo erro não ocorria.
Print em anexo.
Se puder dar uma olhada e me retornar.
Valeu!
![osstudios-pagseguro](https://f.cloud.github.com/assets/2153924/209420/66159108-826b-11e2-9aa0-39441603f76c.jpg)

**Comment by tiagosampaio** [comment]
Olá Pablo,

Tudo bem?
Cara, muito provavelmente o erro está em seu OneStepCheckout, no IndexController e no updateordermethodAction.
Como os endereços estão configurados em seu módulo/loja?

Abraço,

Tiago Sampaio

**Comment by pablotischer** [comment]
Bem e ai.
Então, a questão é que se eu uso o seu módulo anterior do PagSeguro, funciona, mas com este novo não.
Estou usando o checkout da O2ti.

**Comment by pablotischer** [comment]
Quer que eu envie algum arquivo para você dar uma olhada?

**Comment by tiagosampaio** [comment]
@pablotischer,

Por favor, gostaria que enviasse mais informações sobre suas configurações e módulos instalados para que eu possa fazer uma revisão no código.

**Comment by pablotischer** [comment]
Coloquei o módulo do checkout aqui para você dar uma olhada: https://www.dropbox.com/s/1wzhvp83wpldefk/moip_transparente-3.zip?m
E o print da tela do módulo do pagseguro: https://www.dropbox.com/s/y40snqh8hgwg60f/osstudios-pagseguro2.jpg?m
Se precisar de algo mais específico, me avisa que te envio.
Valeu
abraço

**Comment by lpuntel** [comment]
Tiago,
agora também apareceu erro relativo ao endereço. No issue3 reporto erro no nome. Veja e-mail enviado pela loja (não pelo PS)

12:38 AM (13 hours ago)
to me 

Transação de Pagamento Falhou

Razão
 shippingAddressNumber invalid length: {0} 

Tipo de Pagamento
 onepage 

Cliente:
apagado para manter anonimato 

Itens
apagado para manter anonimato

Total:
apagado para manter anonimato

Endereço de Cobrança:
apagado para manter anonimato
 Rua Valdetario Mota xxx (esquina com rua Pascoal de Castro Alves)
 Bairro: Vicente Pinzon
 Fortaleza, Ceará, 60181265
 Brasil
 T: XXX xxx-5102 

Endereço de Entrega:
 apagado para manter anonimato
 Rua Valdetario Mota xxx (esquina com rua Pascoal de Castro Alves)
 Bairro: Vicente Pinzon
 Fortaleza, Ceará, 60181265
 Brasil
 T: xx xxxx-5102 

Forma de Entrega:

Forma de Pagamento:
 PagSeguro UOL 

Data e Hora:
 05/03/2013 00:38:19

**Comment by deivisonarthur** [comment]
Pablo veja se ajuda isso aqui https://gist.github.com/deivisonarthur/5376904

Comigo funcionou! vlw e Tiago parabéns pelo módulo esta top!

**Comment by andersonhonorio** [comment]
Como tenho vários produtos virtuais, fiz algumas alterações:

https://gist.github.com/netShot/5593881

Caso não tenha endereço de entrega, pega o endereço de faturamento.

**Comment by tiagosampaio** [comment]
Olá @pablotischer, @lpuntel, @deivisonarthur e @andersonhonorio,

O problema foi corrigido nesta nova versão do módulo.
Muito obrigado por suas contribuições.

Abraços!

Tiago
