### ISSUE TITLE
Illegal offset type

### ISSUE THREAD

**Issue by aandrade1234** [tiagosampaio/OsStudios_PagSeguroApi#10]
Olá Tiago, inicialmente gostaria de parabenizá-lo pelo excelente módulo.

Estou utilizando o tema Ultimo junto com seu módulo, este tema grava os layouts em um pasta específica, porém copiei as pastas do root base para o ultimo. O módulo está exibindo a matriz de formas de pagamento porém ao finalizar o pedido é exibida uma caixa de diálogo sem nada dentro e nos logs tenho esta mensagem:

2013-05-08T15:37:07+00:00 ERR (3): Warning: Illegal offset type  in /var/www/html/app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Config.php on line 40

Abaixo segue a estrutura de pastas 

? README.md
? app/code/community/OsStudios/PagSeguroApi/Block/Adminhtml/Transaction.php
? app/code/community/OsStudios/PagSeguroApi/Block/Adminhtml/Transaction/Grid.php
? app/code/community/OsStudios/PagSeguroApi/Block/Api/Form.php
? app/code/community/OsStudios/PagSeguroApi/Block/Api/Info.php
? app/code/community/OsStudios/PagSeguroApi/Block/Api/Installments.php
? app/code/community/OsStudios/PagSeguroApi/Block/Api/Success.php
? app/code/community/OsStudios/PagSeguroApi/Controller/Adminhtml/Action.php
? app/code/community/OsStudios/PagSeguroApi/Controller/Front/Action.php
? app/code/community/OsStudios/PagSeguroApi/Helper/Data.php
? app/code/community/OsStudios/PagSeguroApi/Helper/Visie.php
? app/code/community/OsStudios/PagSeguroApi/Model/Abstract.php
? app/code/community/OsStudios/PagSeguroApi/Model/Consulter.php
? app/code/community/OsStudios/PagSeguroApi/Model/Credentials.php
? app/code/community/OsStudios/PagSeguroApi/Model/Data.php
? app/code/community/OsStudios/PagSeguroApi/Model/Mysql4/Payment/History.php
? app/code/community/OsStudios/PagSeguroApi/Model/Mysql4/Payment/History/Collection.php
? app/code/community/OsStudios/PagSeguroApi/Model/Mysql4/Returns/Transaction.php
? app/code/community/OsStudios/PagSeguroApi/Model/Mysql4/Returns/Transaction/Collection.php
? app/code/community/OsStudios/PagSeguroApi/Model/Observer.php
? app/code/community/OsStudios/PagSeguroApi/Model/Payment.php
? app/code/community/OsStudios/PagSeguroApi/Model/Payment/History.php
? app/code/community/OsStudios/PagSeguroApi/Model/Payment/Method/Api.php
? app/code/community/OsStudios/PagSeguroApi/Model/Payment/Method/Api/Xml.php
? app/code/community/OsStudios/PagSeguroApi/Model/Resource/Payment/History.php
? app/code/community/OsStudios/PagSeguroApi/Model/Resource/Payment/History/Collection.php
? app/code/community/OsStudios/PagSeguroApi/Model/Resource/Returns/Transaction.php
? app/code/community/OsStudios/PagSeguroApi/Model/Resource/Returns/Transaction/Collection.php
? app/code/community/OsStudios/PagSeguroApi/Model/Returns.php
? app/code/community/OsStudios/PagSeguroApi/Model/Returns/Transaction.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Config.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Error/Codes.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Shipping/Type.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Transaction/Payment/Methods/Codes.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Transaction/Payment/Methods/Types.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Transaction/Sources.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Transaction/Status.php
? app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Transaction/Types.php
? app/code/community/OsStudios/PagSeguroApi/controllers/Adminhtml/ActionsController.php
? app/code/community/OsStudios/PagSeguroApi/controllers/Adminhtml/TransactionController.php
? app/code/community/OsStudios/PagSeguroApi/controllers/PayController.php
? app/code/community/OsStudios/PagSeguroApi/controllers/ReturnsController.php
? app/code/community/OsStudios/PagSeguroApi/etc/adminhtml.xml
? app/code/community/OsStudios/PagSeguroApi/etc/config.xml
? app/code/community/OsStudios/PagSeguroApi/etc/system.xml
? app/code/community/OsStudios/PagSeguroApi/sql/pagseguroapi_setup/mysql4-install-1.0.0.0.php
? app/design/adminhtml/default/default/layout/osstudios/pagseguroapi.xml
? app/design/adminhtml/default/default/template/osstudios/pagseguroapi/info.phtml
? app/design/frontend/base/default/layout/osstudios/pagseguroapi.xml
? app/design/frontend/base/default/template/osstudios/pagseguroapi/form.phtml
? app/design/frontend/base/default/template/osstudios/pagseguroapi/info.phtml
? app/design/frontend/base/default/template/osstudios/pagseguroapi/installments.phtml
? app/design/frontend/base/default/template/osstudios/pagseguroapi/success.phtml
? app/design/frontend/ultimo/default/layout/osstudios/pagseguroapi.xml
? app/design/frontend/ultimo/default/template/osstudios/pagseguroapi/form.phtml
? app/design/frontend/ultimo/default/template/osstudios/pagseguroapi/info.phtml
? app/design/frontend/ultimo/default/template/osstudios/pagseguroapi/installments.phtml
? app/design/frontend/ultimo/default/template/osstudios/pagseguroapi/success.phtml
? app/etc/modules/OsStudios_PagSeguroApi.xml
? app/locale/pt_BR/OsStudios/PagSeguroApi.csv
? skin/frontend/base/default/css/pagseguroapi/checkout.css
? skin/frontend/base/default/images/pagseguroapi/cards-sprite.gif
? skin/frontend/base/default/images/pagseguroapi/logo-pagseguro.gif

**Comment by tiagosampaio** [comment]
Olá @aandrade1234,
Tudo bem?

Muito obrigado pelo report do bug. Vou verificar.
Apenas para conhecimento, o mesmo problema já está sendo analizado na Issue #11.

Abraços

**Comment by tiagosampaio** [comment]
Olá @aandrade1234.
O problema foi corrigido.

Abraços,

Tiago
