### ISSUE TITLE
Botão "Finalizar Compra" não segue para o PagSeguro

### ISSUE THREAD

**Issue by fernandolucas** [tiagosampaio/OsStudios_PagSeguroApi#11]
Oi Tiago!

Primeiramente parabéns pelo módulo.

Estou com o mesmo problema relatado pelo Maickel, Lauro e Cristine no seu site. Quando eu vou finalizar a comprar e ir para a página do PagSeguro nada acontece. Aparece apenas uma box de mensagem com a url do meu site escrita. Imporante: meu e-mail e Token do PagSeguro estão digitados corretamente.

O estranho é que primeiro instalei a versão que está no MagentoConnect e funcionou perfeitamente. Porém reparei que ela não tem as mesmas opções de configuração e usabilidade da versão do GitHub. Por isso optei pela instalação manual do ZIP do GitHub acreditando que esta é a mais atualizada. Certo?

Uso apenas os módulos OneStepCheckout e Correios by Pedro Teixeira.

No LOG apareceu as seguintes mensagens:

2013-05-11T00:12:39+00:00 ERR (3): Warning: Illegal offset type in /home/patch694/public_html/app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Config.php on line 40

2013-05-11T00:12:39+00:00 ERR (3): Warning: Illegal offset type in /home/patch694/public_html/app/code/community/OsStudios/PagSeguroApi/Model/System/Config/Source/Config.php on line 40

Obrigado pela atenção e novamente parabéns pela iniciativa!

**Comment by fernandolucas** [comment]
Só corrigindo, no box com a mensagem aparece >>> The page at https://patchalmofadas.com.br says: 

Ou seja... Depois dos dois pontos ":" não há nada escrito.

**Comment by tiagosampaio** [comment]
Olá Fernando,

Verificarei o que pode estar acontecendo com o módulo no teu caso.

Abraço,

**Comment by jayveloper** [comment]
Penei 3 dias pra descobrir  o que estava acontecendo... Virei e revirei o código até que consegui imprimir a seguinte mensagem no Alert:

shippingAddressNumber invalid length: {0} 
shippingAddressStreet invalid length: {0}

Pesquisando no Google cheguei até a solução postada pelo Deivison, um dos caras influentes em magento no Brasil assim como o Tiago.

Agradeço a esses 2 caras por suas contribuições.

Valew galera

Agora vamos ao que interessa, a solução encontra-se neste link: https://gist.github.com/deivisonarthur/5670343

Abraços

**Comment by tiagosampaio** [comment]
Olá @fernandolucas  e @jayveloper,

Obrigado por suas contribuições.
Estes problemas já foram corrigidos na nova versão.

Abraços,

Tiago
