### ISSUE TITLE
Painel de Controle - Informação de status

### ISSUE THREAD

**Issue by andersonhonorio** [tiagosampaio/OsStudios_PagSeguroApi#13]
No template pagseguroapi/info.phtml temos :+1: 

```
    <?php if($this->isPaid()):?>
        <?php echo $this->__('The payment was successfully registered in PagSeguro.') ?>
```

Mas, no bloco a função retorna como pago para status = 1

Onde deveria ser 3 ou 4 ( Pago ou Disponivel ) 

```
public function isPaid()
{
    return ( in_array($this->getPagseguroInfo()->getPagseguroTransactionStatus(), array(3,4)) );
}
```

Correto? 

Assim o cliente tera o link disponivel para pagamento.

**Comment by tiagosampaio** [comment]
Olá @netShot, tudo bem?

Agradeço pela dica, porém o código está correto. O método isPaid() retorna simplesmente um boolean informando se a transação está como paga (status 3 ou 4): in_array($this->getPagseguroInfo()->getPagseguroTransactionStatus(), array(3,4)).

Abraços

Tiago Sampaio

**Comment by andersonhonorio** [comment]
Tiago, 

na verdade eu expliquei errado:

Veja:
https://github.com/tiagosampaio/PagSeguroApi-by-OsStudios/blob/master/app/code/community/OsStudios/PagSeguroApi/Block/Api/Info.php

No seu respósitorio, ele faz essa checagem usando == 1

O código que eu postei, foi o que "deveria" ser, correto?
public function isPaid()
{
    return ( in_array($this->getPagseguroInfo()->getPagseguroTransactionStatus(), array(3,4)) );
}
