### ISSUE TITLE
Mudar Status de Pedidos Pagos

### ISSUE THREAD

**Issue by ClovisFilho** [tiagosampaio/OsStudios_PagSeguroApi#14]
Prezado, gostaria de lhe agradecer imensamente pelo desenvolvimento deste módulo.

Estou com uma dúvida a respeito da opção "Mudar Status de Pedidos Pagos Para", presente na aba "Configurações Gerais do PagSeguro". Em minha instalação tenho somente três opções:
- Revisando Pagamento
- Processando
- Congelado

Mesmo quando eu crio um status personalizado, ele não aparece nesta listagem. Gostaria de criar um status com o nome de "Pagamento Aprovado PS". Existe esta possibilidade?

Obrigado pela atenção. Estou no aguardo!

**Comment by tiagosampaio** [comment]
Olá @ClovisFilho,

Sim é possível, porém requer algumas alterações no código.

Abraços,

Tiago
