### ISSUE TITLE
Cálculo incorreto de parcelas

### ISSUE THREAD

**Issue by crisweiser** [tiagosampaio/OsStudios_PagSeguroApi#15]
Conforme printscreen confira a coluna "Valores Finais"

http://prntscr.com/17llbi

**Comment by tiagosampaio** [comment]
Olá @weiser, tudo bem?

Obrigado por sua contribuição. O PagSeguro possui um fator para este cálculo (veja em https://pagseguro.uol.com.br/para_seu_negocio/parcelamento_com_acrescimo.jhtml).
acredito que este deva ser o problema no seu caso.

Abraços,

Tiago
