### ISSUE TITLE
Atualização automática dos status

### ISSUE THREAD

**Issue by ghost** [tiagosampaio/OsStudios_PagSeguroApi#16]
Bom dia Thiago,

Parabéns pelo módulo, funciona muito bem mesmo!!!

Eu só tenho uma dúvida, qdo os pagamentos são pagos, o status muda automaticamente para PENDENTE, por que percebi que só depois que eu entro em:
PagSeguro API -> Ações -> Verificar Status de Pedidos no PagSeguro

é que os status estão sendo atualizados.

Tem como fazer isso automaticamente?

Obrigado!

**Comment by tiagosampaio** [comment]
Olá @maaxxicarvalho, tudo bem?
A atualização automática dos pedidos já está implementado no módulo nativamente. Talvez falte você configurar a URL de notificação no seu painel do PagSeguro.
Você pode configurar a sua URL de notificação no seguinte padrão:

http://www.{url da sua loja}.com.br/pagseguroapi/returns/

Isso deve resolver o seu problema.

Abraços.

Tiago
