### ISSUE TITLE
Após pagamento no pagseguro retorna para a loja virtual no tema padrão 

### ISSUE THREAD

**Issue by Isaquepa** [tiagosampaio/OsStudios_PagSeguroApi#17]
Ola Tiago, sou novato em tudo isso e por falta de recurso estou eu mesmo buscando informações e tentando colocar meu projeto no ar e graças a Deus conseguirei por ter pessoas como vc e Mário Sam.

Minha loja instalei o seu modulo do pagseguro e esta 100% se nao fosse o detalhe de após a finalização do pagamento ao retorno a loja para passar credibilidade ao cliente o retorno se da para um template padrão da loja e nao o meu template personalizado, um detalhe é que quando testo com outro meio de pagamento o retorno acontece para o template correto.

Pode me dar uma luz do que possa estar fazendo de errado?

Abracos

**Comment by ebanolopes** [comment]
Isaquepa, acho difícil que o Magento esteja trocando o template da loja, pois é uma configuração global. A não ser que tenha configurado mais de uma loja, cada uma com um template diferente e o PagSeguro esteja te retornando o endereço da loja secundária; mas acho pouco provável.

O módulo tem uma página de sucesso de compra diferente do padrão, deve estar indo para ela, ao invés da página padrão do Magento. Como customizou a página de sucesso com o template da sua loja e a do módulo ficou sem customização, pode parecer que está saindo do tema. Eu achei inconveniente ter outra página de sucesso, quero que mostre a mesma página que já foi customizada, com todos os dados do pedido. Então criei um módulo que tem um controller que estende o OsStudios_PagSeguroApi_PayController e no método successAction redireciono para a página de sucesso padrão:

```
public function successAction()
{
    $this->_redirect('onepagecheckout/index/success/origin/return');
}
```

Mas vai ter que dar uma olhada na página de sucesso do módulo e pegar o link que direciona para o PagSeguro e incluir ele na sua página de sucesso padrão. Feito isto, está resolvido :)

Bem, faz tempo que postou, deve ter resolvido já, mas se ainda precisar está ai.
