### ISSUE TITLE
[bug] Item amount invalid pattern: 247

### ISSUE THREAD

**Issue by cosmefae** [tiagosampaio/OsStudios_PagSeguroApi#19]
Acabei de atualizar e está aparecendo a seguinte mensagem de erro ao clicar em Checkout:

Error: Item amount invalid pattern: 247. Must fit the patern: \d+.\d{2}  (11029)

Estou usando Magento versão. 1.7.0.2 com o IWD’s One Step Checkout Module.

**Comment by ebanolopes** [comment]
Uso a mesma versão do Magento, não tive este problema, mas provavelmente consegue arrumar facilmente modificando o arquivo OsStudios/PagSeguroApi/Model/Payment/Method/Api/Xml.php, mais especificamente no método getNodeItems, ache a linha abaixo:

$xmlItem->addChild('amount', $this->_formatNumberToXml(($item->getRowTotal() /  $item->getQtyOrdered())));

Aproveite e já previna um erro que relatei neste mesmo método. O módulo não limita a quantidade de caracters da descrição do produto, mas o PagSeguro limita a 100. Modifique a linha da descrição para que fique como abaixo:

$xmlItem->addChild('description', substr($item->getName(), 0, 100));

Abraço!

**Comment by tiagosampaio** [comment]
Olá @cosmefae e @ebanolopes,

Muito obrigado por suas contribuições.
O problema foi corrigido.

Abraços,

Tiago
