### ISSUE TITLE
Call to undefined method SimpleXMLElement::__toString()

### ISSUE THREAD

**Issue by tiagosampaio** [tiagosampaio/OsStudios_PagSeguroApi#2]
Fatal error: Call to undefined method SimpleXMLElement::__toString() in /home/store/public_html/app/code/community/OsStudios/PagSeguroApi/Model/Payment/Method/Api.php on line 207

**Comment by marcelonhenhe** [comment]
Olá Tiago, você tem previsão para quando o erro será consertado?

**Comment by roneclay-zz** [comment]
Estou tendo o mesmo problema. <br />
<b>Fatal error</b>:  Call to undefined method SimpleXMLElement::__toString() in <b>/home/fineweb1/public_html/caixafilosofal/app/code/community/OsStudios/PagSeguroApi/Model/Payment/Method/Api.php</b> on line <b>207</b><br />

**Comment by roneclay-zz** [comment]
Resolvi.

Troquei :

$message = $codes->getNodeByAttribute($error->code->__toString(), 'value', 'message');

Por:

$message = $codes->getNodeByAttribute((string)$error->code, 'value', 'message');

**Comment by LuizSantos1** [comment]
Oi Thiago, aquele problema que eu tinha, parece que desapareceu, mas agora tenho outro:
Error: Item shippingCost invalid pattern: 0. Must fit the patern: \d+.\d{2} (11031) Error: Extra amount invalid pattern: 0. Must fit the patern: -?\d+.\d{2} (11036)

Há alguma solução para isso?
