### ISSUE TITLE
Falha na configuração "Valor Adicional ou Desconto"

### ISSUE THREAD

**Issue by ebanolopes** [tiagosampaio/OsStudios_PagSeguroApi#20]
No arquivo OsStudios/PagSeguroApi/Model/Payment/Method/Api/Xml.php, método getNodeExtraAmount acontece erro quando salva a configuração com algum valor para o campo "Valor Adicional ou Desconto" e depois apaga e salva novamente. A configuração fica vazia, assim como o elemento do XML. Para que não fique vazio, modifiquei o método com cast para float e number_format:

```
protected function _getNodeExtraAmount()
{
    $this->_xml->addChild('extraAmount', number_format((float)$this->_formatNumberToXml(Mage::getStoreConfig('payment/pagseguro_api/extra_amount')), 2, '.', ''));
    return $this;
}
```

**Comment by tiagosampaio** [comment]
Olá @ebanolopes,

Obrigado por sua contribuição ativa com este módulo. Com certeza fará deste módulo melhor para todos.
O problema foi corrigido.

Abraço,

Tiago
