### ISSUE TITLE
Checkout através de "Cadastrar" não redireciona

### ISSUE THREAD

**Issue by Hazazel** [tiagosampaio/OsStudios_PagSeguroApi#24]
Olá pessoal,

verifiquei em meu site que quando os novos clientes realizam o checkout através da opção Cadastrar, os steps seguem normalmente até o botão finalizar compra. Mas quando clicam nesse botão, o pedido é criado, o usuário é registrado, porém não redireciona para o PagSeguro, sem nenhuma mensagem de erro. No pedido backend, há o link para o pagamento, mas este não é enviado para o cliente. Possuo o módulo de checkout padrão do Magento. Para clientes já resgistrados funciona normalmente.

Queria saber se este problema se refere ao módulo OsStudios_PagSeguro_Api, confirmando se vocês também possui este tipo de erro. Ou se é um problema da minha aplicação mesmo.

Agradecimentos,

Alysson Rocha;

**Comment by tiagoceridorio** [comment]
Boa Noite,
Eu tive um problema parecido,consegui corrigir alterando o estado de pagamento pendente de 1 para 3, como informado no manual do pagseguro.
Tem uma isure apontada por mim ai no projeto, de uma olhada lá.

**Comment by Hazazel** [comment]
Obrigado pela resposta Tiago.
Já tinha visto essa issue e arrumei.

Quanto a isso está ok. O modulo altera o status, gera link para pagamento pelo backend etc.

O problema está sendo o redirecionamento de clientes para o site do pagseguro, quando eles, na página de checkout, não fazem o login e, ao invés disso, selecionam a opção "Cadastrar", e colocam lá todas as informações. Chega no step da finalização e não redireciona.

**Comment by Hazazel** [comment]
Resolvido, era problema da minha aplicação mesmo. Quando o cliente seguia pelos passos do checkout através de cadastrar, na finalização do pedido, era enviado um e-mail para o cliente de cadastro, o que afetava o header ficava algo tipo: =?utf-8?B?oicuywquchowckuyeg==?= : emaildocliente@provedor.com 250 Ok 
{"success":true,"error":false,"redirect":"https:\/\/pagseguro.uol.com.br\/v2\/checkout\/payment.html?code=3897XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}. e parece que isso estava quebrando a requisição. Não sei como resolver esse negocio do header do email por enquanto. Por isso fiz um trabalho sujo aqui no Mage/Checkout/Model/Type/Onepage.php (766) : $isNewCustomer = ''; 
Vai ficar assim provisoriamente.

**Comment by Hazazel** [comment]
Edit: Pra que tiver tido o mesmo problema-> Resolvi o problema por completo. Era que a configuração do php mail() no htaccess estava com a opção debug habilitada(on), mudei pra off agora tudo funciona perfeitamente
