### ISSUE TITLE
Aviso de falha no pagamento

### ISSUE THREAD

**Issue by lpuntel** [tiagosampaio/OsStudios_PagSeguroApi#3]
Oi Tiago,
tem ocorrido por algumas vezes a seguinte mensagem enviada pelo site:

Transação de Pagamento Falhou

Razão
 senderName invalid value: {0} 

Tipo de Pagamento
 onepage 

Cliente:
tirado para manter sigilo
Itens
tirado para manter sigilo

Total:
tirado para manter sigilo

Endereço de Cobrança:
 tirado para manter sigilo

Endereço de Entrega:
tirado para manter sigilo
Forma de Entrega:

Forma de Pagamento:
 PagSeguro UOL 

Data e Hora:
 04/03/2013 14:04:08 

Não é sempre que ocorre, e algumas vezes que ocorreu o pagamento foi aprovado pelo PagSeguro.

Isto nunca aconteceu quando tinha seu módulo anterior, então suscita a dúvida.

Como sempre, agradeço pelo suporte
Abs

Puntel

**Comment by lpuntel** [comment]
Tiago, um problema similar fori reportado para este modulo, talvez te ajude na analise- heavenstudio / pag_seguro

**Comment by tiagosampaio** [comment]
Refers to the same issue in #1.
