### ISSUE TITLE
path de returno nao fucionando http://www.sualoja.com.br/pagseguroapi/returns/

### ISSUE THREAD

**Issue by botam** [tiagosampaio/OsStudios_PagSeguroApi#5]
Muito obrigado para o modulo

mas para me essa path de returno nao ta fucionando http://www.minhaloja.com.br/pagseguroapi/returns/

**Comment by tiagosampaio** [comment]
Olá,

Por favor, poderia me dizer como você chegou a conclusão de que não está funcionando?
Como você cadastrou o caminho de retorno?
É importante que você substitua 'www.sualoja.com.br' pelo domínio de sua loja.

Um abraço,

Tiago Sampaio

**Comment by botam** [comment]
PagSeuro ta ajudado agora e seu modulo mesmo

**Comment by tiagosampaio** [comment]
Olá @botam,

Agora a URL de retorno é enviada diretamente na requisição do pagamento, desta forma este processo agora é automatizado.

Abraços,

Tiago
