### ISSUE TITLE
Não envia email

### ISSUE THREAD

**Issue by blopa** [tiagosampaio/OsStudios_PagSeguroApi#9]
O módulo não está enviando o email de confirmação do pedido quando o pedido é finalizado, nem pro cliente nem pro gerente da loja. Quando eu vou na página do pedido tem lá "email não enviado" então não é problema com o meu servidor.

**Comment by tiagosampaio** [comment]
Olá @blopa,

É importante considerar que o Magento apenas envia o e-mail na página de sucesso, ou seja, após o redirecionamento do PagSeguro para o Magento.
A funcionalidade está implementada no módulo, porém é necessário que o cliente retorne à loja e que você habilite a configuração que permite que o Magento envie o e-mail da transação.

Abraço,

**Comment by mbachur** [comment]
Boa tarde, no caso comigo estou usando um tema, so pelo moip nao envia o email de pedido finalizado, quando escolho uma outra qualquer do magento envia o email.
